import React, { useEffect, useState } from 'react';
import type { FactClaimData, FactVerdict, KeyFact } from '../factCheckData';

interface FactResultsProps {
  data: FactClaimData;
  onBack: () => void;
}

// ─── Verdict configuration ────────────────────────────────────────────────────

const verdictConfig: Record<FactVerdict, {
  emoji: string; label: string; color: string; bg: string; border: string;
  headline: string; icon: string;
}> = {
  TRUE: {
    emoji: '✅', label: 'TRUE', color: '#10b981',
    bg: 'rgba(16,185,129,0.08)', border: 'rgba(16,185,129,0.28)',
    headline: 'This claim appears to be accurate.', icon: '✅',
  },
  FALSE: {
    emoji: '❌', label: 'FALSE', color: '#ef4444',
    bg: 'rgba(239,68,68,0.08)', border: 'rgba(239,68,68,0.28)',
    headline: 'This claim is not supported by facts.', icon: '🚫',
  },
  'PARTIALLY TRUE': {
    emoji: '⚠️', label: 'PARTIALLY TRUE', color: '#f59e0b',
    bg: 'rgba(245,158,11,0.08)', border: 'rgba(245,158,11,0.28)',
    headline: 'This claim contains some truth, but is misleading.', icon: '⚠️',
  },
  'NOT ENOUGH INFORMATION': {
    emoji: '❓', label: 'UNVERIFIED', color: '#6366f1',
    bg: 'rgba(99,102,241,0.08)', border: 'rgba(99,102,241,0.25)',
    headline: "We couldn't fully verify this claim.", icon: '❓',
  },
};

const factStatusConfig = {
  confirmed: { emoji: '✅', color: '#10b981', label: 'Confirmed True' },
  disputed:  { emoji: '❌', color: '#ef4444', label: 'Not Supported'  },
  unknown:   { emoji: '❓', color: '#6366f1', label: 'Unknown'        },
};

const sourceTypeIcon: Record<string, string> = {
  government: '🏛️', scientific: '🔬', news: '📰', factcheck: '🔍',
};

// ─── Verdict Meter ────────────────────────────────────────────────────────────

const meterWidths: Record<FactVerdict, number> = {
  TRUE: 90, FALSE: 10, 'PARTIALLY TRUE': 50, 'NOT ENOUGH INFORMATION': 50,
};

const VerdictMeter: React.FC<{ verdict: FactVerdict; color: string }> = ({ verdict, color }) => {
  const [w, setW] = useState(0);
  useEffect(() => { const t = setTimeout(() => setW(meterWidths[verdict]), 100); return () => clearTimeout(t); }, [verdict]);

  return (
    <div style={{ width: '100%' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.7rem', fontWeight: 700, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 8 }}>
        <span>❌ False</span><span>⚠️ Partial</span><span>✅ True</span>
      </div>
      <div style={{ height: 14, borderRadius: 999, background: 'linear-gradient(90deg, #ef4444 0%, #f59e0b 50%, #10b981 100%)', position: 'relative', boxShadow: 'var(--shadow-inset)' }}>
        <div style={{ position: 'absolute', inset: 0, borderRadius: 999, background: 'rgba(0,0,0,0.12)' }} />
        <div style={{
          position: 'absolute', left: `${w}%`, top: '50%',
          transform: 'translate(-50%,-50%)',
          width: 26, height: 26, borderRadius: '50%',
          background: '#fff', border: `3.5px solid ${color}`,
          boxShadow: `0 2px 14px ${color}80`,
          transition: 'left 1.3s cubic-bezier(0.34,1.56,0.64,1)',
          zIndex: 2, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '0.9rem',
        }}>
          {verdictConfig[verdict].icon}
        </div>
      </div>
    </div>
  );
};

// ─── Main Component ───────────────────────────────────────────────────────────

export const FactResultsDashboard: React.FC<FactResultsProps> = ({ data, onBack }) => {
  const cfg = verdictConfig[data.verdict];

  const downloadReport = () => {
    const lines = [
      `SafeCheck Reel Fact-Check Report`,
      `=================================`,
      ``,
      `Reel Analyzed`,
      `-------------`,
      `URL: ${data.reelUrl}`,
      `Account: ${data.account}`,
      `Reel ID: ${data.reelId}`,
      ``,
      `Claim Found in Reel`,
      `-------------------`,
      data.claimFound,
      ``,
      `Verdict: ${data.verdict}`,
      `Category: ${data.category}`,
      `Confidence: ${data.confidenceLabel}`,
      ``,
      `Why This Verdict`,
      `----------------`,
      data.reason,
      ``,
      `Key Facts Checked`,
      `-----------------`,
      ...data.keyFacts.map(f => `${f.status === 'confirmed' ? '✓' : f.status === 'disputed' ? '✗' : '?'} ${f.point} — ${f.status.toUpperCase()}`),
      ``,
      `Sources Consulted`,
      `-----------------`,
      ...data.sources.map(s => `• ${s.name}: ${s.url}`),
      ``,
      `What to Watch Out For`,
      `---------------------`,
      ...data.tips.map((t, i) => `${i + 1}. ${t}`),
      ``,
      `Generated by SafeCheck Fact Checker · ${new Date().toLocaleDateString()}`,
      `Results are for informational purposes only.`,
    ];
    const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = `safecheck-reel-${data.reelId}.txt`;
    a.click();
  };

  return (
    <div className="results-wrapper">

      {/* Back */}
      <button onClick={onBack} className="btn-back" id="fact-back-btn" style={{ marginBottom: '2rem' }}>
        <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
          <path d="m15 18-6-6 6-6" />
        </svg>
        <span>Check another reel</span>
      </button>

      {/* ══════════════════════════════════════════════════
          SECTION A0: Reel Info Card
      ══════════════════════════════════════════════════ */}
      <div className="results-card" style={{ padding: '1.25rem 1.5rem' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', flexWrap: 'wrap' }}>
          {/* Reel thumbnail stand-in */}
          <div style={{
            width: 72, height: 72, borderRadius: 14, flexShrink: 0,
            background: 'linear-gradient(135deg, #f58529, #dd2a7b, #8134af)',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            fontSize: '2rem', boxShadow: '0 4px 16px rgba(221,42,123,0.35)',
            position: 'relative', overflow: 'hidden',
          }}>
            <div style={{ position: 'absolute', inset: 0, background: 'linear-gradient(180deg,rgba(255,255,255,0.15) 0%,transparent 50%)' }} />
            <span style={{ position: 'relative', zIndex: 1 }}>{data.thumbnailEmoji}</span>
          </div>

          <div style={{ flex: 1, minWidth: 0 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4, flexWrap: 'wrap' }}>
              <span style={{
                fontSize: '0.7rem', fontWeight: 800, textTransform: 'uppercase',
                letterSpacing: '0.06em', padding: '2px 9px', borderRadius: 999,
                background: 'linear-gradient(135deg,rgba(245,133,41,0.12),rgba(129,52,175,0.12))',
                border: '1px solid rgba(221,42,123,0.25)', color: '#dd2a7b',
              }}>📹 Instagram Reel</span>
              <span style={{ fontSize: '0.77rem', color: 'var(--text-muted)', fontWeight: 600 }}>ID: {data.reelId}</span>
            </div>
            <div style={{ fontWeight: 700, fontSize: '0.9rem', color: 'var(--primary)', marginBottom: 3 }}>{data.account}</div>
            <p style={{ fontSize: '0.82rem', color: 'var(--text-secondary)', lineHeight: 1.5, margin: 0 }}>{data.claimSummary}</p>
          </div>

          <a
            href={data.reelUrl}
            target="_blank"
            rel="noopener noreferrer"
            id="view-reel-link"
            style={{
              display: 'inline-flex', alignItems: 'center', gap: 6,
              padding: '0.5rem 1rem', borderRadius: 9,
              background: 'linear-gradient(135deg, #f58529, #dd2a7b)',
              color: '#fff', textDecoration: 'none',
              fontSize: '0.78rem', fontWeight: 700,
              boxShadow: '0 3px 12px rgba(221,42,123,0.4)',
              flexShrink: 0, whiteSpace: 'nowrap',
              transition: 'opacity 0.18s ease',
            }}
            onMouseEnter={e => (e.currentTarget as HTMLElement).style.opacity = '0.88'}
            onMouseLeave={e => (e.currentTarget as HTMLElement).style.opacity = '1'}
          >
            <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
              <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6" />
              <polyline points="15 3 21 3 21 9" /><line x1="10" y1="14" x2="21" y2="3" />
            </svg>
            View Reel
          </a>
        </div>
      </div>

      {/* ══════════════════════════════════════════════════
          SECTION A: Big Verdict Card
      ══════════════════════════════════════════════════ */}
      <div className="results-overview-card" style={{ border: `2px solid ${cfg.border}`, background: cfg.bg }}>
        {/* Extracted claim label */}
        <div style={{
          background: 'var(--bg-glass)', border: '1px solid var(--border-color)',
          borderRadius: 12, padding: '0.9rem 1.1rem', marginBottom: '1.5rem',
          fontSize: '0.88rem', color: 'var(--text-secondary)', lineHeight: 1.65,
          position: 'relative',
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 7, marginBottom: 8 }}>
            <span style={{ fontSize: '0.68rem', fontWeight: 800, textTransform: 'uppercase', letterSpacing: '0.07em', color: 'var(--primary)' }}>
              🎙️ Claim extracted from reel
            </span>
          </div>
          <p style={{ fontStyle: 'italic', margin: 0 }}>
            "{data.claimFound.length > 220 ? data.claimFound.slice(0, 220) + '…' : data.claimFound}"
          </p>
        </div>

        {/* Verdict badge row */}
        <div style={{ display: 'flex', alignItems: 'center', gap: '1.5rem', flexWrap: 'wrap', marginBottom: '1.5rem' }}>
          <div style={{
            display: 'inline-flex', alignItems: 'center', gap: 12,
            padding: '0.9rem 1.75rem', borderRadius: 9999,
            background: cfg.color, color: '#fff',
            fontWeight: 900, fontSize: '1.3rem', letterSpacing: '-0.01em',
            boxShadow: `0 4px 24px ${cfg.color}60, inset 0 1px 0 rgba(255,255,255,0.2)`,
          }}>
            <span>{cfg.emoji}</span>
            <span>{cfg.label}</span>
          </div>
          <div>
            <div style={{ fontWeight: 700, fontSize: '1rem', color: 'var(--text-primary)', marginBottom: 2 }}>{cfg.headline}</div>
            <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>Category: {data.category} · Confidence: {data.confidenceLabel}</div>
          </div>
        </div>

        <VerdictMeter verdict={data.verdict} color={cfg.color} />
      </div>

      {/* ══════════════════════════════════════════════════
          SECTION B: Why This Verdict
      ══════════════════════════════════════════════════ */}
      <div className="results-card">
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: '1rem' }}>
          <div style={{ width: 36, height: 36, borderRadius: 10, background: cfg.bg, border: `1px solid ${cfg.border}`, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '1.2rem', flexShrink: 0 }}>💡</div>
          <h3 style={{ fontWeight: 800, fontSize: '1rem', color: 'var(--text-primary)', letterSpacing: '-0.01em' }}>Why This Verdict?</h3>
        </div>
        <p style={{ fontSize: '0.93rem', color: 'var(--text-secondary)', lineHeight: 1.78 }}>{data.reason}</p>
      </div>

      {/* ══════════════════════════════════════════════════
          SECTION C: Key Facts Checked
      ══════════════════════════════════════════════════ */}
      <div className="results-card">
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: '1.1rem' }}>
          <div style={{ width: 36, height: 36, borderRadius: 10, background: 'rgba(99,102,241,0.08)', border: '1px solid rgba(99,102,241,0.2)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '1.2rem', flexShrink: 0 }}>📋</div>
          <h3 style={{ fontWeight: 800, fontSize: '1rem', color: 'var(--text-primary)', letterSpacing: '-0.01em' }}>Key Claims We Checked</h3>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
          {data.keyFacts.map((fact: KeyFact, i) => {
            const sc = factStatusConfig[fact.status];
            return (
              <div key={i} style={{
                display: 'flex', alignItems: 'flex-start', gap: 12,
                padding: '0.85rem 1rem', borderRadius: 12,
                background: fact.status === 'confirmed' ? 'rgba(16,185,129,0.06)' : fact.status === 'disputed' ? 'rgba(239,68,68,0.06)' : 'rgba(99,102,241,0.06)',
                border: `1px solid ${fact.status === 'confirmed' ? 'rgba(16,185,129,0.2)' : fact.status === 'disputed' ? 'rgba(239,68,68,0.2)' : 'rgba(99,102,241,0.2)'}`,
              }}>
                <span style={{ fontSize: '1.1rem', flexShrink: 0, marginTop: 1 }}>{sc.emoji}</span>
                <div style={{ flex: 1 }}>
                  <span style={{ fontSize: '0.88rem', color: 'var(--text-primary)', lineHeight: 1.55 }}>{fact.point}</span>
                </div>
                <span style={{ fontSize: '0.68rem', fontWeight: 800, textTransform: 'uppercase', letterSpacing: '0.05em', color: sc.color, flexShrink: 0, alignSelf: 'center' }}>
                  {sc.label}
                </span>
              </div>
            );
          })}
        </div>
      </div>

      {/* ══════════════════════════════════════════════════
          SECTION D: Sources
      ══════════════════════════════════════════════════ */}
      <div className="results-card">
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: '1.1rem' }}>
          <div style={{ width: 36, height: 36, borderRadius: 10, background: 'rgba(37,99,235,0.08)', border: '1px solid rgba(37,99,235,0.18)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '1.2rem', flexShrink: 0 }}>📚</div>
          <h3 style={{ fontWeight: 800, fontSize: '1rem', color: 'var(--text-primary)', letterSpacing: '-0.01em' }}>Trusted Sources Consulted</h3>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(240px, 1fr))', gap: '0.85rem' }}>
          {data.sources.map((src, i) => (
            <a
              key={i}
              href={src.url}
              target="_blank"
              rel="noopener noreferrer"
              id={`source-link-${i}`}
              style={{
                display: 'flex', alignItems: 'center', gap: 12,
                padding: '0.9rem 1rem', borderRadius: 12,
                background: 'var(--bg-glass)', border: '1px solid var(--border-color)',
                textDecoration: 'none', transition: 'all 0.18s ease', cursor: 'pointer',
              }}
              onMouseEnter={e => { (e.currentTarget as HTMLElement).style.borderColor = 'var(--border-color-hover)'; (e.currentTarget as HTMLElement).style.background = 'var(--bg-glass-strong)'; }}
              onMouseLeave={e => { (e.currentTarget as HTMLElement).style.borderColor = 'var(--border-color)'; (e.currentTarget as HTMLElement).style.background = 'var(--bg-glass)'; }}
            >
              <span style={{ fontSize: '1.3rem', flexShrink: 0 }}>{sourceTypeIcon[src.type] || '🔗'}</span>
              <div style={{ flex: 1, minWidth: 0 }}>
                <div style={{ fontWeight: 700, fontSize: '0.85rem', color: 'var(--primary)', marginBottom: 1, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{src.name}</div>
                <div style={{ fontSize: '0.7rem', color: 'var(--text-muted)', textTransform: 'capitalize' }}>{src.type.replace('factcheck', 'Fact-Check Organization')}</div>
              </div>
              <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="var(--text-muted)" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ flexShrink: 0 }}>
                <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6" /><polyline points="15 3 21 3 21 9" /><line x1="10" y1="14" x2="21" y2="3" />
              </svg>
            </a>
          ))}
        </div>
      </div>

      {/* ══════════════════════════════════════════════════
          SECTION E: What to Watch Out For
      ══════════════════════════════════════════════════ */}
      <div className="results-card">
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: '1.1rem' }}>
          <div style={{ width: 36, height: 36, borderRadius: 10, background: 'rgba(245,158,11,0.08)', border: '1px solid rgba(245,158,11,0.22)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '1.2rem', flexShrink: 0 }}>👁️</div>
          <h3 style={{ fontWeight: 800, fontSize: '1rem', color: 'var(--text-primary)', letterSpacing: '-0.01em' }}>What to Watch Out For</h3>
        </div>

        <div className="action-list">
          {data.tips.map((tip, i) => (
            <div key={i} className="action-item">
              <div className="action-check" style={{ background: 'linear-gradient(135deg, #f59e0b, #fbbf24)' }}>
                <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z" /><circle cx="12" cy="12" r="3" />
                </svg>
              </div>
              <span style={{ fontSize: '0.88rem', color: 'var(--text-secondary)', lineHeight: 1.55 }}>{tip}</span>
            </div>
          ))}
        </div>
      </div>

      {/* ══════════════════════════════════════════════════
          SECTION F: Download
      ══════════════════════════════════════════════════ */}
      <div className="results-download-bar">
        <div>
          <div style={{ fontWeight: 700, fontSize: '0.95rem', color: 'var(--text-primary)', marginBottom: 2 }}>Save or share this fact-check</div>
          <div style={{ fontSize: '0.78rem', color: 'var(--text-muted)' }}>Download a text report to share with others</div>
        </div>
        <button id="fact-download-btn" className="btn-analyze" onClick={downloadReport} style={{ flexShrink: 0, padding: '0.7rem 1.5rem', fontSize: '0.88rem' }}>
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
            <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" /><polyline points="7 10 12 15 17 10" /><line x1="12" y1="15" x2="12" y2="3" />
          </svg>
          Download Report
        </button>
      </div>

      <p style={{ textAlign: 'center', fontSize: '0.73rem', color: 'var(--text-muted)', lineHeight: 1.6, margin: '0.75rem auto 0', maxWidth: 560 }}>
        ⚠️ This fact-check is based on available public information. Verdicts may not reflect breaking developments. Always consult multiple sources.
      </p>
    </div>
  );
};
